### ISSUE TITLE
Spelling Errors

### ISSUE THREAD

**Issue by kieron76** [NigelGreenway/bashful-thoughts#6]
echo in install.bash prints '/' where it should be a '.'

src/bashful-thoughts.utilty.bash - utility is spelt wrong and is spelt correctly in the above echo statement.

I can push my fix if you like?

**Comment by NigelGreenway** [comment]
@kieron76 already working on a fix with that as I spotted it on Friday, but been hectic this weekend. Want to get the changes merged in by tomorrow night if that's okay?

**Comment by kieron76** [comment]
yeah sure no rush :+1:
